[template]
cargo_generate_version = ">=0.0.1"
include = ["README.md"]

[hooks]
# init = ["init_script.rhai"]

[placeholders]
description = { type = "string", prompt = "Description for the crate?" }
username = { type = "string", prompt = "Name for the user?" }


