[template]
cargo_generate_version = ">=0.0.1"
include = ["README.md"]

[hooks]
# init = ["init_script.rhai"]

[placeholders]
username = { type = "string", prompt = "Name for the user?" }

[demo.'hello']

[demo.'blink']
port = { type="string", prompt="Port of GPIO is used to LED, eg. B", regex = "^[a-fA-F]$"}
pin = { type="integer", prompt="Pin of GPIO is used to LED, eg. 5", range = [0, 15] }


